name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.89.0

      - name: Setup Solana, Anchor & Node.js
        uses: solana-developers/github-actions/setup-all@v0.2.9
        with:
          solana_version: "2.1.21"
          anchor_version: "0.32.1"
          node_version: "20"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Anchor program
        run: anchor build

      - name: Run tests
        run: anchor test
